### ISSUE TITLE
Stuff from Slides Presentation

### ISSUE THREAD

**Issue by briankleinqiu** [berkeley-stat159/project-theta#105]
- Investigate mask thresholds, possibly customize for each one
- Mention that there might be movement in the scanner
- Change the box plots to dots
- Clarify mixed effects model is 16 models, one for the three runs of each subject 
- Variance Map on the brain, show RMS for example on heat map

**Comment by BenjaminHsieh** [comment]
- Plot actual numbers (dots instead of boxplot)
- Rim around edges suggest motion, comment on this
- specify mixed effects: what is random is the trials, not subjects, since we dont have a standard brain to map to
- Potentially: Variance map across brain

**Comment by BenjaminHsieh** [comment]
Did we address all these points, especially specifying the mixed model and boxplot to scatter plot/ interpret possible movement in our paper?
@changsiyao @boyinggong

**Comment by boyinggong** [comment]
Done !

**Comment by BenjaminHsieh** [comment]
closing
