### ISSUE TITLE
Final report draft feedback

### ISSUE THREAD

**Issue by rossbar** [berkeley-stat159/project-theta#107]
- Your methods description is very clear, but you need to show your results.
  For instance, at the end of section 3.1.1 you say "we acheived almost the
  same results as the paper". This doesn't carry any actual meaning: show the
  results of your logistic regression, show the results from the paper, and 
  compare them
- same goes for the rest of section 3.1 - these descriptions are very clear
  and concise, but where are the results?
- you seem to have a very concrete plan, but there are no results to provide
  feedback on. 
- For comparison across subjects, you should look into the data Matthew posted
  that aligns data across the subjects. There's also the lecture on 
  transforming the coordinate system of the brain images. These two things 
  should be sufficient to overcome the issues you highlight in section 3.3

**Comment by changsiyao** [comment]
I'm sorry, but I don't think you are looking at our newest paper. We originally put our new paper in a draft directory. Then Jarrod asked us to fix it and change it to the paper directory. However, I think you made the pull before we were able to fix it.
Could you possibly look at our new paper, which is in the paper directory right now? Sorry for the inconvenience.

**Comment by rossbar** [comment]
Yes I will look at it, though I may not be able to get around to it today. I will take a look asap

**Comment by rossbar** [comment]
Here is feedback on the paper as it was in commit f3888539f7581eae2b4c4235b28019c699928e35
- In figure 3: what is the green line? Is it a least-squares fit to your data? What is the model and what point do you intend to make with the fit? Either clarify what the green line is (including a legend in the plot
  would be a good start) and why it's there, or remove it.
- In section 3.3, when you are enumerating your assumptions: For assumption 4, is it enough to look for correlations over the time dimension? Since you're using neural data, I'm assuming the residuals you are measuring are in the voxel-space. Would spatial correlation between errors have an effect on your interpretation of the results? This train of thought applies to figure 4 as well, where you appear to be plotting the residuals over the time course for a single voxel.
- In section 4.1: be more clear about what you mean by "accuracy". I assume you mean the ability of the model to correctly predict whether a subject will gamble given the "gain" and "loss" coefficients. Is this correct? Do the model results vary significantly between the different subjects? How does this compare to the results from the paper? You state that the results of your model are consistent with the paper: it would be much more convincing if you actually showed your results next to the paper results in the same plot.
- In figures 7-9: the colorbar should be scaled the same for each axis within the image for comparison's sake. Look into the vmin and vmax kwargs to imshow() to figure out how to do this. Also, the data looked smoothed: is this the result of explicit spatial smoothing on your part or the built-in image interpolation from imshow?
- In section 5.1.2: you should have the capability to map to the MNI template based on Matthew's lectures. Related: in section 5.2.1 - large data size is NOT a good motivation for not using the preprocessed data. The registered data is required in order to make comparisons between subjects that are in any way meaningful. I realize it's pretty late in the project now, but if you are planning on drawing any conclusion about inter-subject comparisons I strongly recommend you take another stab at trying to understand and use the data Matthew provided (also, it doesn't make sense that the preprocessed data would be significantly larger than the unpreprocessed data)

**Comment by BenjaminHsieh** [comment]
Thanks for feedback, addressed everything, closing now
