### ISSUE TITLE
mapping from millmeter coordinate to voxel coordinates

### ISSUE THREAD

**Issue by changsiyao** [berkeley-stat159/project-theta#109]
What should we do when we don't get integer voxel coordinates. Do you round the coordinates to integers?
For example, in our paper, the mm coordinate is (3.6, 6.3, 3.9), when we turn it into voxel coordinate, it is (43.2, 66.15, 37.95).

Thanks!
@matthew-brett @jarrodmillman @rossbar

**Comment by matthew-brett** [comment]
Could you say a little more about what you are intending to do with the coordinate value?

If you just want to get an approximate voxel coordinate to get the voxel closest to the corresponding mm coordinate, then rounding is the right thing to do.

**Comment by changsiyao** [comment]
In our paper, the authors looked at a part of the brain with the mm coordinate (3.6, 6.3, 3.9). We want to look at the same part of the brain. We want to compare the beta values of the neural regression for that part of the brain with the beta values of the behavior regression.

**Comment by matthew-brett** [comment]
In that case it would be reasonable to round the voxel coordinates - that would give you the nearest voxel corresponding to their mm coordinate.

**Comment by matthew-brett** [comment]
OK to close this one?

**Comment by changsiyao** [comment]
Thank you!
