### ISSUE TITLE
Organization, Makefile, Readme Finalize

### ISSUE THREAD

**Issue by BenjaminHsieh** [berkeley-stat159/project-theta#114]
To DO:
1. Organize functions/graphing in utils, should place graphing functions separately since we dont have tests for them and coverage report not good as of now
2. Update our scripts so figures/data txt files saves to (perferably) a single location, maybe the paper directory.
3. Delete old paper directory
4. Update the Makefiles for directories: project-theta, code, data, paper
    - Be sure the make coverage produces the correct reports
    - Be sure all `make` commands produce the correct results, eg all tests run smoothly
5. Update/add the readme on all the following directories: project-theta, code, data, paper
    - Document all `make` commands 
    - Include instructions to show user how to navigate each respective directory, eg how to download data, make figures for paper, the steps to building our paper, etc
    - Other documentation (in main directory): our names, project overview, acknowledgements

**Comment by BenjaminHsieh** [comment]
Lets try to get all the current pull requests cleared ASAP and do 1, 2, 3 above

**Comment by briankleinqiu** [comment]
Can we make the latest graphing scripts available? We need to start adapting the regression functions and scripts to the new template data, not sure what's going on there

**Comment by BenjaminHsieh** [comment]
I think @changsiyao @pigriver123 were working on the new scripts with standard template,

**Comment by changsiyao** [comment]
The heatmap scripts requires calculating beta first, should I add the scripts to the regression script, or make a new script and just copy and paste the calculating beta part

**Comment by changsiyao** [comment]
Also need to find a good threshold for the new standard data. @brianqiu Could you look into that? I did 7000 for now, not sure if it's a good idea.

**Comment by BenjaminHsieh** [comment]
I think ideally we should only run the calc beta function once, save the results in data_results directory and load it in for other functions, or else every script will run hella slow

**Comment by changsiyao** [comment]
OK, we can save the beta values in a txt file, that's not too bad.
But we also need to calculate the t values, so should we calculate the t values in the regression script and save that as well? (I think that's most efficient, since calculating t values need the design X and BOLD data Y.)
What do you think?

**Comment by briankleinqiu** [comment]
Ok from running a script for the filtered data, it loos like 8000 is a good threshold for every subject/run, perhaps 7500 if we're being conservative. It takes a looong time to run on the data so I'll just add the image here.

Also just wondering, are we using the template mask?

For the t-values, perhaps it'll be more efficient to store the design and y and whatever data we need? Just my two cents
![mean_hists_filtered](https://cloud.githubusercontent.com/assets/14049646/11760624/9068a556-a056-11e5-9500-67d4fa08704c.png)

**Comment by changsiyao** [comment]
We don't want to store Y, cuz Y is just the BOLD data, so it's really big. I say, let's just calculate t and store the t values, which should be much smaller.
And I'm not sure how to use the template mask? What is it suppose to do?

**Comment by BenjaminHsieh** [comment]
I think calculating t-values is a lot less expansive than calcuating betas right? if you dont need t-values for more than 1 script we can just calcuate it inthe scripts and make figures from those t-values. Either way is fine but just keep in mind our end goal is produce figures and tables

@brianqiu do you know how to use template mask?

**Comment by BenjaminHsieh** [comment]
Also, anyone not coding the final figures should start editing the paper draft, its crunch time

**Comment by briankleinqiu** [comment]
The template mask is just a 0 for values est. outside of the brain and a 1 for the ones inside. I'll check this afternoon to see if we need to use it, we might not.

**Comment by briankleinqiu** [comment]
For the final paper I assume we're going to use the 'paper' directory and not make a new one

**Comment by BenjaminHsieh** [comment]
yes, also please save any data results in paper/data_results
