### ISSUE TITLE
Add the new data/template and mni stuff to gitignore

### ISSUE THREAD

**Issue by BenjaminHsieh** [berkeley-stat159/project-theta#133]
@brianqiu can you add the new data into the .gitignore in the project directory? thanks

**Comment by briankleinqiu** [comment]
Should I add the filtered func data in addition to the templates?

Edit: nvm. i see ds005 already ignored in your pull request. in that case i'll merge the request and edit it

**Comment by BenjaminHsieh** [comment]
yep thanks
