### ISSUE TITLE
Need to edit code, scipt makefiles and readmes

### ISSUE THREAD

**Issue by BenjaminHsieh** [berkeley-stat159/project-theta#138]
Waiting for all the scripts to come in and we will need to update the makefiles and readmes accordingly
@pigriver123 please comment when all sciprts are done

**Comment by BenjaminHsieh** [comment]
Check #144

**Comment by pigriver123** [comment]
@BenjaminHsieh I think I have added all the scripts

**Comment by briankleinqiu** [comment]
For the readmes whats the threshold for warning the user about run time. some of the scripts take ~15 minutes

**Comment by BenjaminHsieh** [comment]
Not sure but you can just add the estimated run times in the readme, I just labeld the things that take more than 45 mins

**Comment by BenjaminHsieh** [comment]
closing
