### ISSUE TITLE
Need to add paperfig make command

### ISSUE THREAD

**Issue by BenjaminHsieh** [berkeley-stat159/project-theta#139]
Waiting for all figures to be saved in paper/figures, then edit makefile by adding `make paperfig` to move the corresponding figures from `results/figures` into `paper/figures`

**Comment by changsiyao** [comment]
Looks like Boying separated the paper/figures folder into even smaller folders.
Also, for some figures, she combined them into one (not using python scripts), so we need to keep those figures in the folder in order for our paper to use...

**Comment by BenjaminHsieh** [comment]
@boyinggong how did you combine the figures? Can we make it reproducible (eg combine using latex)? I will be heading out for finals soon be back after 6.

**Comment by boyinggong** [comment]
I did not combine them using latex. I think using latex make them every sparse and ugly :) then I do it manually. I think it doesn't matter for this?

**Comment by BenjaminHsieh** [comment]
closing
