### ISSUE TITLE
Data/makefile

### ISSUE THREAD

**Issue by briankleinqiu** [berkeley-stat159/project-theta#14]
We need to:

(1) pull in the data files when we run makefile. can do this either thru bash commands or calling a python file, i think we should consider making a python file

(2) generate a hash for each file

(3) make sure we validate it in the data.py test

Comment any thoughts

**Comment by BenjaminHsieh** [comment]
refer to pull request #20, @changsiyao may have to submit a new pull request

**Comment by changsiyao** [comment]
I asked ross, he said, we should check the hash for every single file in the unzipped folder... But he also said that would be more complicated so if we really don't feel like doing it, we don't have too... I'll see if I have time to write some loops for that...

**Comment by changsiyao** [comment]
Please check pull request #24 , everything should pass now.

**Comment by BenjaminHsieh** [comment]
closing b/c #29 was merged
