### ISSUE TITLE
List of issues discovered when running make files

### ISSUE THREAD

**Issue by changsiyao** [berkeley-stat159/project-theta#141]
In graph_lindiag_script.py, from graph_lindiagnostics import qqplot, res_var needs to be done from the utils/graphing folder.

*\* should be taken care of, please check #143

**Comment by changsiyao** [comment]
We generated the results folder, but not the subfolders /texts/ and /figures/

*\* Done #144

**Comment by changsiyao** [comment]
Also, when I unzip the ds005 mnifunc file, all the files are store in the ds005 folder with the raw data, instead of having a new ds005_mnifunc folder?
Does anybody else get that? if so, I need to change the path in the standard data regression script.

*\* should be taken care of, please check #143

**Comment by changsiyao** [comment]
fix bugs in standard heatmaps scripts
update makefile with standard heatmaps

*\* should be taken care of, please check #143

**Comment by BenjaminHsieh** [comment]
Another issue I found: in `plot_heatmap_standard.py`
lines 83 and 95, `img=axis.imshow(t_gain[:, :, plot_number], cmap=plt.get_cmap('rainbow'), alpha=0.5,interpolation='nearest',vmin=t_gainmin, vmax=t_gainmax)` and `img=axis.imshow(t_loss[:, :, plot_number], cmap=plt.get_cmap('rainbow'), alpha=0.5,interpolation='nearest',vmin=tlossmin, vmax=tlossmax)
`

The `t_gainmin/t_gainmax` and `tlossmin/tlossmax` are not defined, please check @changsiyao @pigriver123

**Comment by pigriver123** [comment]
I will correct this one

**Comment by pigriver123** [comment]
I have defined t_gainmin/t_gaminmax,...in plot_heatmap_standard.py,please check @BenjaminHsieh

**Comment by changsiyao** [comment]
fixed t_gainmin/max issue, please check #145

**Comment by briankleinqiu** [comment]
Reminder to selves, we may have to change makefile/readme for paper depending on how #142 turns out

**Comment by briankleinqiu** [comment]
When you run make glm does anyone get
" ../utils/functions/calc_t.py:40: RuntimeWarning: invalid value encountered in double_scalars
  t2= numerator2 / denominator2"

I'm using python 2

**Comment by changsiyao** [comment]
I also get that, but I think it's ok, it happens when denominator is 0, and I think it returns nan, which is what we would've changed the 0's to anyway.

**Comment by BenjaminHsieh** [comment]
Remember to address everything on Ross' comments in #107

**Comment by briankleinqiu** [comment]
In plot_neural_behavior in utils/graphing, Y is undefined. Is it still the bold signal
@changsiyao @pigriver123 @BenjaminHsieh @boyinggong

**Comment by BenjaminHsieh** [comment]
yeah I will change it to `neural` in my current pull request 
See #150

**Comment by BenjaminHsieh** [comment]
closing
