### ISSUE TITLE
office hour questions

### ISSUE THREAD

**Issue by boyinggong** [berkeley-stat159/project-theta#27]
1. What is the dependent variable of the neural regression model?
2. What is the PTval in the behadata?
3. Can we run R from python? The supplemental material mentioned that they use R to fit Logistic regression.
4. Why we should run a mixed effects model? Can we just run a multiple regression model and combine the 3 runs for a subject together? If we fit the mixed effects model for the neural data, then we also have to do it for behav data?

**Comment by BenjaminHsieh** [comment]
1. dependent is the y matrix (t (time) X V (number of voxels))
2. Dont know what PTval is, probably just ignore
3. Yes, but as supplementary analysis. So not really recommended.
4. Can just try without mixed model for now and run regression on pooled runs or individually, mention in our discussion section of the paper of this limitation. Also one idea is to compare mixed and non-mixed by writing R-scripts with mixed model and comparing it to python non-mixed. 
   @boyinggong anything else to add?

**Comment by BenjaminHsieh** [comment]
closing addressed points
