### ISSUE TITLE
feedback

### ISSUE THREAD

**Issue by jarrodmillman** [berkeley-stat159/project-theta#60]
Had a nice introduction to the concept of loss-aversion and what their paper
was studying (it was one of the clearest of the introductions on the
loss-aversion study).

Only group that really introduced the models they were intending to use. They've
clearly done a good job reading and understanding their paper.

Preliminary results/preprocessing results were noticably absent; a lot of
focus on information from the paper.  Seemed a bit behind in working with the
fMRI data.

Overall, seemed to have a very nice conceptual understanding of your study,
but really need to get working with the data. Your presented goal was
reasonable and feasible (propose to repeat the analysis in the paper to
validate the models and regression techniques used) but it seemed like very
little concrete work has materialized toward that end.

You need to make sure you are writing valid code.  For example, you can't use
np.something, if np doesn't exist.

**Comment by BenjaminHsieh** [comment]
closing, thanks for feedback
