### ISSUE TITLE
Idea: Brain anatomy plotting / T-value plotting

### ISSUE THREAD

**Issue by BenjaminHsieh** [berkeley-stat159/project-theta#63]
For t-value plotting, can we try to reproduce something like this?
![hypothesis_testing](https://cloud.githubusercontent.com/assets/10675933/11266380/fc56b5d8-8e58-11e5-9c27-4f1c9361682f.png)

Where we plot the mean t-value (across all 16 subjects) at various cross sections of the brain, we might want to ask tomorrow how we can utilize the anatomy data, I feel like that might important for plotting

**Comment by BenjaminHsieh** [comment]
Graph credit to project alpha

**Comment by briankleinqiu** [comment]
As for the part about anatomy data, did we ever figure that out? Are we looking into the standard brain template in the minifunc dataset from lecture, or the brain mask from piazza (also in minifunc dataset)
