### ISSUE TITLE
Heatmaps showing up wierd

### ISSUE THREAD

**Issue by BenjaminHsieh** [berkeley-stat159/project-theta#83]
the first set of heatmaps shows up weird

**Comment by changsiyao** [comment]
What do you mean by weird?

**Comment by boyinggong** [comment]
Mine seems OK.

**Comment by BenjaminHsieh** [comment]
umm... they are plotting on several pages for me, anyway if it look good for you all then lets merge this dev to master and open a issue for jarrod

**Comment by changsiyao** [comment]
They were originally too big, so I shrink the fig size. I thought they should look ok now.
There are three different heatmaps, btw

**Comment by BenjaminHsieh** [comment]
ok can you merge my latest pull request and are we good to merge to master?

**Comment by changsiyao** [comment]
We also have duplicated further research sections...

**Comment by BenjaminHsieh** [comment]
yeah the new pull request should fix that, can you check/pull the new version

**Comment by changsiyao** [comment]
OK, I see it now.

**Comment by BenjaminHsieh** [comment]
TO DO:
Merge to master
Also:
Can you guys build the final version and send it to Jarrod via email, make issue, mention jarrod with @, and direct him to the draft directory? thanks, pull request the final pdf as well as the tex into our repository online

**Comment by BenjaminHsieh** [comment]
Cool are we good?

**Comment by changsiyao** [comment]
I can produce a final pdf, but what do you mean by "as well as the tex"?

**Comment by BenjaminHsieh** [comment]
oh i meant the tex files, which we have already

**Comment by changsiyao** [comment]
So you want a pdf in our repo as well?

**Comment by BenjaminHsieh** [comment]
yeah just in case things dont work when he makes

**Comment by BenjaminHsieh** [comment]
you can close this issue when everything is done, I need to leave the computer for 10 min, thanks everyone!

**Comment by changsiyao** [comment]
Eh... what's jarrod's email?

**Comment by changsiyao** [comment]
Email sent
